### PR TITLE
Add some translations (Portuguese-BR)

### PR DESCRIPTION
**Pull request by gandradeiasi**

### CODE REVIEW

**Comment by dorkster** [comment]
Thanks. I squashed your commits into a single commit to keep things tidy.

**Comment by vmonteirobr** [comment]
Hi guys, i have a question.
This merge sync with transiflex project? I don’t see contributor Gabriel in transiflex project team.
Have concern that translation work do not having a syncing.

Hi Gabriel, send-me a message to talk about how we improve the translation, thanks

**Comment by dorkster** [comment]
@vmonteirobr Whenever I merge translations on Github, I push them to Transifex. It shows up on the activity list as a contribution by me (see screenshot):

screenshot_2018-06-11_00-15-06

This way, not all translators are forced to use Transifex. Some people just don't want to have a Transifex account, and that's okay with us.

**Comment by dorkster** [comment]
@gandradeiasi Thanks for joining. It definitely makes things easier on our end.

**Pull request merged**
