### PR TITLE
gd translation update

### PR DESCRIPTION
**Pull request by gunchleoc**

### CODE REVIEW

**Comment by gunchleoc** [comment]
I just asked on the forum if we can extend the translation deadline until next week. I really need the weekend for the Empyrean campaign.

**Comment by dorkster** [comment]
If you need the weekend, could you have it done by Monday? We plan to release on the 12th, so we could sneak it in.

**Comment by dorkster** [comment]
If you really need more time, we can always put out a patch post-release. So don't worry too much if you can't make the deadline.

**Comment by gunchleoc** [comment]
I'll try to make Monday, thanks!

A patch also sounds good in case I don't make it, thanks for offering :)

**Pull request merged**
