### PR TITLE
further translation of alpha-demo and fantasycore

### PR DESCRIPTION
**Pull request by Jeffry84**
Hi, I've installed the latest version from github as dorkster suggested. Much better although I don't see the option to change the resolution :/

A couple of questions: 
Is it better to have more split lines for every entry as the previous translator did or on a single line as the original lines are? Is it safe to remove those lines I left empty?
I don't know if what I mean is understandable, if you have a look at alpha-demo/data.it.po you might understand what I mean.

### CODE REVIEW

**Comment by dorkster** [comment]
Thanks.

We removed the resolution option because the game's graphics (designed for 640x480) now scale to the window size. Try resizing the window to see what I mean. This solved the issue where the player's viewport would be very different depending on their screen resolution (e.g. high resolutions seeing the whole map).

I personally think keeping strings on a single line is better, but it's a matter of opinion. You can remove the empty lines safely as far as I know.

If it's okay with you, I would prefer if you squashed all of these commits into one:

```
git rebase -i 51232fa
git push -f origin patch-1
```

Note, this will rewrite the git history and require a force push. If you're unsure about doing that, do the rebase on a new branch and send a pull request to that instead:

```
git checkout -b translation
git rebase -i 51232fa
git push origin translation
```

**Comment by Jeffry84** [comment]
You can freely merge all my edits into one; the previous entries are 
intermediate saves because I did my edits at different times. About the 
force push I don't know how to do it: I downloaded the final files to 
try them on my installation, I can copy and paste them in another patch 
once I try to reinsert all the lines in one entry and get rid of the 
typos (I can spellcheck 1000 times and still I can find some... Grrr)
I'll resize the window to get close to my usual resolution then. Thanks 
to you :)

Il 08/09/2015 00:18, Justin Jacobs ha scritto:

**Comment by dorkster** [comment]
Okay, don't worry about doing a rebase and push then. I can take care of that after the fact.

**Comment by dorkster** [comment]
Oh, and just in case you had planned on it: Don't worry about translating the empyrean_campaign mod yet. I'm am still working on it, so strings are changing frequently. We'll make an announcement when we want translators to help out with that.

**Comment by Jeffry84** [comment]
Ok, I was considering it but I'll wait for the annoucement. I'll check the forum every now and then.

**Comment by dorkster** [comment]
Your changes are now here: https://github.com/clintbellanger/flare-game/commit/0135c5f5f20f710038d9ba65ded38af39de6ae02

**Comment by Jeffry84** [comment]
Wonderful, thanks. I'll update my local files and change them here when ready.

**Pull request closed without merging**
